<?php
/**
 * The header for our theme.
 *
 * This is the template that displays all of the <head> section and everything up until <div id="content">
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package Lyndascore
 */

?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<div id="page" class="hfeed site">
	<a class="skip-link screen-reader-text" href="#content"><?php esc_html_e( 'Skip to content', 'lyndascore' ); ?></a>

	<header id="masthead" class="site-header" role="banner">

        <?php
        // first check if there is a header image and text is blank
        if( get_header_image() && !('blank' == get_header_textcolor()) ){
            //if we have a header image and text is not blank get the header image, if not just display div below
            //Use get_header_image() when using echo otherwise in php use header_image like above.
            echo ' <div class="site-branding" style="background-image:url(' . get_header_image() . ' );width:100%;
            height:100%;"> ';
        } else {

            echo ' <div class="site-branding"> ';
        }

        ?>

            <h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
            <p class="site-description"><?php bloginfo( 'description' ); ?></p>

        </div><!-- .site-branding -->

		<nav id="site-navigation" class="main-navigation" role="navigation">
			<button class="menu-toggle" aria-controls="primary-menu" aria-expanded="false"><?php esc_html_e( 'Primary Menu', 'lyndascore' ); ?></button>
			<?php
            //print out the menu
            wp_nav_menu( array( 'theme_location' => 'primary', 'menu_id' => 'primary-menu' ) ); ?>

            <!-- THe link targets the search container ID - hides the text and marked up to be translated -->
            <div class="search-toggle">
                <i class="fa fa-search"></i>
                <!-- PHP displays translated text Search for the theme name-->
                <a href="#search-container" class="screen-reader-text"><?php esc_html_e('Search', 'lyndascore') ?></a>
            </div>

            <?php swp_social_menu(); ?>
		</nav><!-- #site-navigation -->

        <!-- Search form itself-->
        <div id="search-container" class="search-box-wrapper clear">
            <div class="search-box clear">
            <!-- default form generated by WP-->
                <?php get_search_form(); ?>

            </div>
        </div>

	</header><!-- #masthead -->

	<div id="content" class="site-content">
